spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 60000

service:
  frontend:
    url: ${FRONTEND_SERVICE_URL}
  ai:
    url: ${AI_SERVICE_URL}
    secret-key: ${AI_BACKEND_KEY}
  map:
    url: ${MAP_SERVICE_URL}

springdoc:
  swagger-ui:
    enabled: false