spring:
  application:
    name: backend-api

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  flyway:
    locations: classpath:db/migration
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
  
  threads:
    virtual:
      enabled: true

server:
  port: 8081

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-expiration: 86400000
      refresh-expiration: 604800000

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs
    operations-sorter: method