name: AI CI
on:
  push:
    branches:
      - main
    paths:
      - 'Python/AI/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'Python/AI/**'

jobs:
  build-image:
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    name: Build Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v6
        with:
          context: Python/AI
          platforms: linux/amd64
          push: true
          file: Python/AI/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/dating-route-ai:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/dating-route-ai:latest
